image: golang:1.15

pipelines:
  default:
    - parallel:
      - step:
          name: &build-app
          script:
            # Build compiles the packages
            - go build hello-world.go
      - step:
          name: Lint code
          image: golangci/golangci-lint:v1.31.0
          script:
            - golangci-lint run -v
  branches:
    main:
      # Use * for alias
      - step:
          name: Deploy to Server
          script:
            - go build hello-world.go
            - apt-get update && apt-get install -y git
            - git config --global user.email "osher@bitbucket.com"
            - git config --global user.name "Osher"
            - git init
            - if git remote | grep -q 'origin'; then git remote set-url origin https://${USERNAME}:${GITHUB_TOKEN}@github.com/${USERNAME}/${REPO}.git; else git remote add origin https://${USERNAME}:${GITHUB_TOKEN}@github.com/${USERNAME}/${REPO}.git; fi
            - git pull origin main --allow-unrelated-histories
            - git add .
            - git commit -m "Automated commit from Bitbucket pipeline"
            - git push -u origin main
